TEXTS = {
    'uz': {
        'choose_language': "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Choose language",
        'welcome': "Assalomu alaykum! ESL loyihasiga xush kelibsiz! 🎓\n\nIltimos, ro'yxatdan o'ting:",
        'enter_name': "To'liq ismingizni kiriting:",
        'enter_phone': "Telefon raqamingizni ulashing:",
        'share_contact': "📱 Kontaktni ulashish",
        'enter_age': "Yoshingizni kiriting (ixtiyoriy, tashlab ketishingiz mumkin):",
        'skip': "⏭ Tashlab ketish",
        'enter_region': "Viloyatingizni tanlang:",
        'registration_complete': "✅ Ro'yxatdan o'tish muvaffaqiyatli yakunlandi!\n\nEndi to'lov qilishingiz kerak.",
        'main_menu': "🏠 Asosiy menyu",
        'payment': "💳 To'lov",
        'questions': "❓ Savollar",
        'faq': "📋 FAQ",
        'ask_question': "❓ Savol berish",
        'settings': "⚙️ Sozlamalar",
        'referral': "👥 Referal",
        'payment_instruction': "To'lov uchun kvitansiya skreenshotini yuboring:",
        'payment_sent': "✅ To'lovingiz ko'rib chiqish uchun yuborildi!",
        'payment_approved': "🎉 To'lovingiz tasdiqlandi! Guruh linki:",
        'payment_rejected': "❌ To'lovingiz rad etildi. Iltimos, qaytadan urinib ko'ring.",
        'enter_question': "Savolingizni yozing:",
        'question_sent': "✅ Savolingiz yuborildi!",
        'your_referral_link': "Sizning referal havolangiz:\n{link}\n\nReferal soni: {count}\nTo'lov qilganlar: {paid}",
        'no_faq': "Hozircha FAQ bo'sh.",
        'change_age': "Yoshni o'zgartirish",
        'change_name': "Ismni o'zgartirish",
        'change_number': "Raqamni o'zgartirish",
        'change_city': "Shaharni o'zgartirish",
        'change_language': "Tilni o'zgartirish",
        'language_changed': "✅ Til muvaffaqiyatli o'zgartirildi!",
        'changes_saved': "✅ Muvaffaqiyatli o'zgartirildi!",
        'regions': [
            "Toshkent sh.", "Toshkent vil.", "Samarqand", "Buxoro", "Andijon",
            "Farg'ona", "Namangan", "Qashqadaryo", "Surxondaryo", "Jizzax",
            "Sirdaryo", "Navoiy", "Xorazm", "Qoraqalpog'iston"
        ]
    },
    'ru': {
        'choose_language': "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Choose language",
        'welcome': "Добро пожаловать в проект ESL! 🎓\n\nПожалуйста, зарегистрируйтесь:",
        'enter_name': "Введите ваше полное имя:",
        'enter_phone': "Поделитесь вашим номером телефона:",
        'share_contact': "📱 Поделиться контактом",
        'enter_age': "Введите ваш возраст (необязательно, можете пропустить):",
        'skip': "⏭ Пропустить",
        'enter_region': "Выберите ваш регион:",
        'registration_complete': "✅ Регистрация успешно завершена!\n\nТеперь вам нужно оплатить.",
        'main_menu': "🏠 Главное меню",
        'payment': "💳 Оплата",
        'questions': "❓ Вопросы",
        'faq': "📋 FAQ",
        'ask_question': "❓ Задать вопрос",
        'settings': "⚙️ Настройки",
        'referral': "👥 Реферал",
        'payment_instruction': "Отправьте скриншот квитанции об оплате:",
        'payment_sent': "✅ Ваш платеж отправлен на рассмотрение!",
        'payment_approved': "🎉 Ваш платеж подтвержден! Ссылка на группу:",
        'payment_rejected': "❌ Ваш платеж отклонен. Пожалуйста, попробуйте снова.",
        'enter_question': "Напишите ваш вопрос:",
        'question_sent': "✅ Ваш вопрос отправлен!",
        'your_referral_link': "Ваша реферальная ссылка:\n{link}\n\nКоличество рефералов: {count}\nОплативших: {paid}",
        'no_faq': "FAQ пока пуст.",
        'change_age': "Изменить возраст",
        'change_name': "Изменить имя",
        'change_number': "Изменить номер",
        'change_city': "Изменить город",
        'change_language': "Изменить язык",
        'language_changed': "✅ Язык успешно изменен!",
        'changes_saved': "✅ Изменения сохранены!",
        'regions': [
            "г. Ташкент", "Ташкентская обл.", "Самарканд", "Бухара", "Андижан",
            "Фергана", "Наманган", "Кашкадарья", "Сурхандарья", "Джизак",
            "Сырдарья", "Навои", "Хорезм", "Каракалпакстан"
        ]
    },
    'en': {
        'choose_language': "🇺🇿 Tilni tanlang / 🇷🇺 Выберите язык / 🇬🇧 Choose language",
        'welcome': "Welcome to ESL project! 🎓\n\nPlease register:",
        'enter_name': "Enter your full name:",
        'enter_phone': "Share your phone number:",
        'share_contact': "📱 Share contact",
        'enter_age': "Enter your age (optional, you can skip):",
        'skip': "⏭ Skip",
        'enter_region': "Choose your region:",
        'registration_complete': "✅ Registration completed successfully!\n\nNow you need to make a payment.",
        'main_menu': "🏠 Main menu",
        'payment': "💳 Payment",
        'questions': "❓ Questions",
        'faq': "📋 FAQ",
        'ask_question': "❓ Ask question",
        'settings': "⚙️ Settings",
        'referral': "👥 Referral",
        'payment_instruction': "Send a screenshot of your payment receipt:",
        'payment_sent': "✅ Your payment has been sent for review!",
        'payment_approved': "🎉 Your payment has been approved! Group link:",
        'payment_rejected': "❌ Your payment was rejected. Please try again.",
        'enter_question': "Write your question:",
        'question_sent': "✅ Your question has been sent!",
        'your_referral_link': "Your referral link:\n{link}\n\nReferral count: {count}\nPaid referrals: {paid}",
        'no_faq': "FAQ is empty for now.",
        'change_age': "Change age",
        'change_name': "Change name",
        'change_number': "Change number",
        'change_city': "Change city",
        'change_language': "Change language",
        'language_changed': "✅ Language changed successfully!",
        'changes_saved': "✅ Changes saved successfully!",
        'regions': [
            "Tashkent city", "Tashkent region", "Samarkand", "Bukhara", "Andijan",
            "Fergana", "Namangan", "Kashkadarya", "Surkhandarya", "Jizzakh",
            "Sirdarya", "Navoiy", "Khorezm", "Karakalpakstan"
        ]
    }
}
